services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    restart: always
    networks:
      - casdoor-net

  casdoor:
    image: casbin/casdoor:latest
    container_name: casdoor-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DRIVER_NAME=sqlite3
      - DATABASE_SOURCE=/data/casdoor.db
      - SYNC_OR_REPLACE=true
      - GIN_MODE=release  # Disable debug mode
      - CACHE_SIZE=500    # Reduce cache entries
    volumes:
      - ./data:/data  # Persists database and assets
    networks:
      - casdoor-net
    # Critical resource limits for 1GB RAM device:
    mem_limit: 500m
    cpus: 0.5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # Auto-update and backup service
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 86400 --cleanup --label-enable
    restart: always
    networks:
      - casdoor-net   

networks:
  casdoor-net: